events {}

http {
    resolver 8.8.8.8 valid=5s;

    server {
        listen 80 default_server;

        auth_request /auth-check;
        error_page 401 = @redirect_to_portal;

        location /auth-check {
            internal;
            proxy_pass http://192.168.100.3:3000/api/check;
            proxy_pass_request_body off;
            proxy_set_header Content-Length "";
            proxy_set_header X-Real-IP $remote_addr;
        }

        location @redirect_to_portal {
            return 302 http://$host/splash;
        }

        location /splash/ {
            auth_request off;
            alias /usr/share/nginx/html/;
        }

        location = /splash {
            auth_request off;
            root /usr/share/nginx/html;
            try_files /index.html =404;
        }

        location /api/ {
            auth_request off;
            proxy_pass http://192.168.100.3:3000;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location / {
            set $upstream http://httpbin.org;
            proxy_pass $upstream;
        }
    }
}
